### PR TITLE
Use Minitest live integration tests instead of Shindo mocked tests

### PR DESCRIPTION
**Pull request by ihmccreery**
This is a pull request to remove old Shindo tests backed by mocks in the codebase, in favor of live integration tests built on Minitest.

See the updated CONTRIBUTING for information on the design of the tests and how to run them.

This change is motivated by a few things:

1. The Shindo tests were backed by mocks in the codebase, which didn't provide any assurance that the code actually worked, only that it was internally consistent.  This led to drift away from the API as code was written and tested against the mocks, but not continually tested against the live API.  In turn, the mocks were hard to keep up-to-date.
1. Per fog/fog#1266 and fog/fog#2630, Minitest is the new testing framework to be used by fog projects.

There are a few outstanding issues that are related to this.  I'm also opening #50 to track this whole migration from shindo to `minitest`.

### CODE REVIEW

**Comment by ihmccreery** [comment]
I will squash commits once we're happy with the way the merge looks.

**Comment by ihmccreery** [comment]
@plribeiro3000 @tokengeek @geemus Your input on how I've structured tests here would be greatly appreciated.

**Comment by plribeiro3000** [comment]
Thats a pretty big diff. Let me take a look at it in the next weekend!

Great job btw!

**Comment by geemus** [comment]
Awesome, thanks!

@plribeiro3000 I'll leave it to you for now, but just let me know if you have questions or need help.

**Comment by plribeiro3000** [comment]
@geemus thank you for reminding me of that.

@ihmccreery there are a lot of specifix changes here that i wont comment since they are related to how the provider works. All the code seems to be OK. I might ler something uncovered but i believe you will fix any issue this might introduce.

So you have my big :+1: for all this coding and documentation.

**Comment by geemus** [comment]
@ihmccreery Looking good, but appears there are some build failures, could you double check those? Thanks!

**Comment by ihmccreery** [comment]
Sorry I'm leaving this on the table for a bit; I'm caught up in other things right now.

The Travis issue is just a configuration issue: the way I wrote the Rakefile, Travis is running integration tests that it's not configured to run.  Related to #19, which may be a barrier to merging this.

**Comment by geemus** [comment]
@ihmccreery alright, just let me know if there is anything I can do to help further here.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
