### PR TITLE
Remove failing compute and storage test suites

### PR DESCRIPTION
**Pull request by Everlag**
These tests are written against the old api client, hence they
will always fail as we are no longer providing excon responses.
These will be rewritten as their corresponding functionality is
reimplemented.

Having these gone now should make for cleaner diffs on storage
and compute tests.

This has the same effect as #218 did but favors removal rather
than carrying inactive tests forward.

### CODE REVIEW

**Comment by Everlag** [comment]
Can you point out the `collection` tests which should be passing? I'm having some trouble finding them and would rather not delete working examples.

**Comment by Temikus** [comment]
Those are collection tests (ending with `_collection`):
test_compute_addresses_collection.rb
test_compute_networks_collection.rb
, they should be request-independent. If something's broken in them - we most likely have broken something.

**Comment by Temikus** [comment]
Also, while we're at it - did you see the Travis errors about no `managed_zones` method?

**Comment by Everlag** [comment]
I agree, the collection tests should eventually pass, I'll remove them from this change.

For the managed_zones error, I've only been considering the minitest suites, would you prefer the shindo tests also be handled here?

**Comment by Everlag** [comment]
I've updated this PR to not conflict with the half-merged Storage changes, #231 and #233. I think this is worth looking at to get useful results out of concourse while we migrate the api client.

**Comment by icco** [comment]
Just going to close for now, may revisit later.

**Pull request closed without merging**
