### PR TITLE
Ruby 3 does not support Proc.new without arguments

### PR DESCRIPTION
**Pull request by sethboyles**
Co-authored-by: Seth Boyles <sboyles@pivotal.io>
Co-authored-by: Merric de Launey <mdelauney@pivotal.io>

### CODE REVIEW

**Comment by sethboyles** [comment]
@geemus can we get this merged and released?  thanks

**Review by geemus — APPROVED** [review]
LGTM.

**Comment by geemus** [comment]
Released in v1.19.0.

**Comment by sethboyles** [comment]
thanks!

**Pull request merged**
