### PR TITLE
Bumping Google API client to 0.23

### LINKED ISSUE #325: google-api-client >= 0.20 support
Hello!

`google-api-client` 0.20.0 is out and it's required to work with Ruby 2.5 (https://github.com/google/google-api-ruby-client/pull/648) Would it be possible to bump the dependency for that lib in gemspec?

### PR DESCRIPTION
**Pull request by Temikus**
Fixes #325

### CODE REVIEW

**Comment by Temikus** [comment]
Welp, something broke in client initialization across minor versions. Sigh.

**Comment by Temikus** [comment]
`google/apis/resourceviews_v1beta2` has disappeared

**Comment by Temikus** [comment]
Yep, that's the API that was decomissioned a while ago. I'll quickly fix this.

**Comment by Temikus** [comment]
All tests pass, merging.

**Comment by icco** [comment]
Thanks for this!

**Pull request merged**
