### PR TITLE
Expose Storage pre-signed object delete url

### PR DESCRIPTION
**Pull request by nolith**
This PR exposes pre-signed URLs for Google Cloud Storage

### CODE REVIEW

**Comment by icco** [comment]
Hi @nolith! Thanks for the PR. This actually looks like it might be better served by modifying https://github.com/fog/fog-google/blob/master/lib/fog/storage/google_json/requests/get_object_https_url.rb to have an optional argument of `method` that defaults to `"GET"`, that way we don't need to create a new file for every single request type. What do you think?

**Comment by nolith** [comment]
Hi @icco thank you.

Looking at the code base I had the impression that each kind of request is supposed to be on a different class loaded with `request`.

This is exactly the same way `get_object`/`get_object_url` and `put_object`/`put_object_url` is implemented.

Adding an optional parameter to `get_object_https_url` it's a bit strange to me because I had the impression that `get_` doesn't mean _getter_ method but it's the name of the remote operation API, which is _GetObject_

**Comment by nolith** [comment]
The [same PR](https://github.com/fog/fog-aws/pull/431) has merged and released by fog-aws.

I would love to remove this monkey-patching from my production code.
Please @icco  let me know what can I do to bring this forward. 🙏 

Thanks

**Comment by nolith** [comment]
No problem. Thank you

**Pull request merged**
