### PR TITLE
Add support for subnetworks

### PR DESCRIPTION
**Pull request by drcapulet**

### CODE REVIEW

**Comment by icco** [comment]
I totally missed that this got released. Thanks @drcapulet 

https://cloud.google.com/compute/docs/subnetworks

**Comment by icco** [comment]
@drcapulet, Would you be interested in implementing mocks? That's the only thing that looks to be missing, but not crucial.

**Comment by drcapulet** [comment]
@icco updated with mocks + specs!

**Comment by icco** [comment]
THANKS! :+1:

**Pull request merged**
