### PR TITLE
Upgrade google-api-client to 0.9

### PR DESCRIPTION
**Pull request by icco**
This is in preparation to deal with https://github.com/google/google-api-ruby-client/issues/336, and also something we've wanted to do for a while.

The description of what we need to do is https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md

Opening this PR just so people know I'm working on it, not ready to merge yet.

### CODE REVIEW

**Comment by DawidJanczak** [comment]
Any news on this and/or help needed?

**Comment by icco** [comment]
I haven't had a chance to touch this. We'll need to rewrite most of our api integrations because of the scope of the change in 0.9.

**Comment by apraditya** [comment]
Do you have a branch for this? How can I help?

**Comment by icco** [comment]
This is the branch, but I've put absolutely no time into it. If you'd like to help, it's probably worth just starting from scratch yourself.

**Comment by krainboltgreene** [comment]
Now that Rails 5 is standard this PR is going to be of greater and greater importance as 0.8.Z versions of google-api-client depend on an older version of ActiveSupport, making it incompatible with rails 5.

**Comment by icco** [comment]
Closed in favor of #210.

**Pull request closed without merging**
