### PR TITLE
Add ability to check single instance health

### PR DESCRIPTION
**Pull request by Temikus**
WIP for #162 Do not merge yet.

@selmanj PTAL, did you have something like this in mind?

### CODE REVIEW

**Comment by selmanj** [comment]
Yeah, that'll do it (although it'd be nice if we could eliminate the conditional).

Speaking of, it looks like this takes a full instance url here; do we have any sort of convention on when to use the instance name vs the whole name within fog-google? I can see both sides (full url is clearer, but often redundant and annoying to type/find) and I'm curious what you think.

**Comment by Temikus** [comment]
Well, the conditional will be there anyway, I should probably dedup the request logic though.
Taking a closer look at this - I think the logic should probably be moved to the model. Request really should just be a google-api-client proxy, requesting a single instance status. This will simplify a one-off call tremendously too, WDYT?

On the instance url, we prefer `instance_name`. However, I don't know how the API will behave in the future, so I don't want to guess the zone in this request.

**Comment by selmanj** [comment]
Agreed on moving the logic to the model. You can make it backwards compatible by supporting the old behavior when instance name isn't provided (maybe with a deprecated message?)

**Comment by Temikus** [comment]
@selmanj Cool, I'll start extracting.

I do not agree on deprecating the old behaviour though. I'd rather insert a rescue somewhere in the enumeration cycle. The thing is - Fog is designed to make cloud platform access easier. The current load balancer API is very difficult to work with, so we do some lifting on our side that the user can get more useful info.

**Comment by selmanj** [comment]
Well, I was just advocating that you maintain the current behavior in the request method, but log a message saying the right place to satisfy this request is using the model class (since requests should just be simple request-based logic).  Then, sometime in the future you could remove the duplicated logic from the request code.

**Comment by Temikus** [comment]
@selmanj PTAL

@icco - please, check whether the deprecation makes sense and if you agree with the returned data. I remember you used this.

**Pull request merged**
