### PR TITLE
Add support for using predefined ACLs, fixes #324

### LINKED ISSUE #324: Storage#put_object_acl does not accept canned ACLs
Hi Folks,

I admit my use case is rather strange as I tend to use the lower level API methods and requests as opposed to the models, and I realise I can use the models if I need to. I'm intending on setting an ACL long after an object has been uploaded to the bucket, and so I'd like to avoid downloading the object in order to re-upload it.

However, onto my problem - I am trying to use the `put_object_acl` method/request in the following manner `connection.put_object_acl(bucket_name, object_name, 'public-read')`, which is [officially supported in the XML API documentation](https://cloud.google.com/storage/docs/xml-api/put-object-acls) (see the blue note).

At the moment, the code is not set up to look for a predefined ACL as the third argument, and instead expects a Hash from which it can construct the request body. I would like to use predefined ACLs, as is [supported by the AWS equivalent request](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/storage/put_object_acl.rb#L39). I'm looking at forking the repo at the moment and getting stuck in if you don't mind.

Thanks for reading. :)

-- easkay

### PR DESCRIPTION
**Pull request by easkay**
As per issue #324, I decided to make a start on this functionality and would like to know what folks think. I'm not sure which tests need writing and where, especially since things are migrating to minitest. Some guidance would be appreciated.

Also, the changes introduced here are pretty much entirely copied from https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/storage/put_object_acl.rb#L39.

### CODE REVIEW

**Comment by easkay** [comment]
@icco No worries, thanks for taking a look. I'll work on your feedback later this evening and update the PR. I notice there's no mock for this request either, do you have any suggestions on making one? Not a problem if you don't :)

**Comment by icco** [comment]
@easkay I was hoping you could update the File and Directory models as well that are using public acls. As for mocks, usually copying the response from google by making the request with curl and then scrubbing data is how it's been done in the past.

**Comment by easkay** [comment]
@icco Ah, sorry I misunderstood and/or misread. I'll get on that in a few minutes :) Apologies for the misunderstanding.

**Comment by easkay** [comment]
@icco I wasn't entirely sure where these should live. Utils seems like a good place on the surface of it, what do you think?

**Comment by icco** [comment]
Thanks so much!

**Pull request merged**
