### PR TITLE
Upgrade google client to 0.15

### PR DESCRIPTION
**Pull request by icco**
This is very much ongoing, but I'd love a first pass whenever people get a chance. Using this branch because #100 never really got going.

Work is being tracked in #226

### CODE REVIEW

**Comment by icco** [comment]
Oh my god, this is going to be such a pain in the ass. Basically need to read through https://github.com/google/google-api-ruby-client/tree/master/generated/google/apis and use it to rewrite all of requests, and a little bit of every method. Oh, and all mocks.

Example working change: lib/fog/dns/google/requests/get_project.rb, lib/fog/dns/google/models/projects.rb and lib/fog/dns/google/real.rb

**Comment by icco** [comment]
(Also contributions welcome, because in no way am I going to be able to get all of this done)

**Comment by DawidJanczak** [comment]
Question - with the previous version it was possible to inject `google_client` and, by doing so we could use the Google Compute service account to fetch the access token. Something like described here: http://holyhandgrenade.org/blog/2014/09/using-google-compute-engine-service-accounts-with-fog/ Now on this branch we can no longer pass this option, but I think we could in theory inject the authorization directly into Google Api Client as described here https://github.com/google/google-api-ruby-client#passing-authorization-to-requests
Do you think that would work? And if so could the requirement for `google_json_key_location` or `google_json_key_string` to be present be lifted?

**Comment by icco** [comment]
@DawidJanczak You can't create API clients anymore, but we could have it so you pass in a [GoogleAuth](https://github.com/google/google-auth-library-ruby) object.

**Comment by DawidJanczak** [comment]
Thanks @icco! I tried it here https://github.com/fog/fog-google/compare/upgrade-google-client...DawidJanczak:upgrade-google-client-auth, but can't make it work. I keep getting `google has no storage service` error from `fog` Tried injecting it like this:
```ruby
auth = Google::Auth.get_application_default
AUTH = auth.fetch_access_token

Paperclip::Attachment.default_options[:fog_credentials][:google_auth] = AUTH
```
Is it simply not working because the PR is not ready yet or am I doing something wrong?

**Comment by icco** [comment]
@DawidJanczak yeah, this PR is no where near ready. Haven't done the storage migration yet. If that's something you'd be interested in helping with, I can gladly walk you through it.

**Comment by icco** [comment]
Oh but @DawidJanczak your change is what we'd need to re-add auth passing back.

**Comment by DawidJanczak** [comment]
@icco I'll gladly help out, but will certainly need your help. Let me know what needs to be done and I'll take a look as soon as possible.

**Comment by wurde** [comment]
This is desperately needed for anyone using the google-cloud gem. I'm getting the following errors.

google-cloud-bigquery-0.24.0 depends on google-api-client (~> 0.10.0)
google-cloud-dns-0.22.0 depends on google-api-client (~> 0.10.0)
google-cloud-resource_manager-0.22.0 depends on google-api-client (~> 0.10.0)
google-cloud-storage-0.24.0 depends on google-api-client (~> 0.10.0)

**Comment by icco** [comment]
@werde those errors seem unrelated. Please open a new issue with more details.

**Comment by connorshea** [comment]
@icco we use this at GitLab, thank you for your work. I'll see if I can get someone from the team to help out.

**Comment by icco** [comment]
@connorshea sweet. I wrote up a longer howto doc for @DawidJanczak who I think is going to try and tackle storage. If there is a certain subsection you'd like to work on, feel free to shoot me an email at nat@natwelch.com with fog-google in the subject and I can send you the same details.

**Comment by Everlag** [comment]
Do we want to add an `integrate` tag so concourse runs against this PR?

**Comment by icco** [comment]
Alright all, I'm merging this in tomorrow. We'll do a 1.0 release early next week. Thanks everyone for their help.

**Comment by connorshea** [comment]
@icco 🎉 thank you for the work on this!

**Comment by johnsonj** [comment]
awesome work @icco @emilymye @DawidJanczak @Everlag - thank you all!

**Pull request merged**
