### PR TITLE
Move Storage files to the expected path

### PR DESCRIPTION
**Pull request by plribeiro3000**
cc/ @Temikus 

Ongoing process to make fog-google follow the standards and avoid performance issues when loading the entire fog ecosystem as in fog/fog#3430

Consider merging after #102 and #103 .

### CODE REVIEW

**Comment by Temikus** [comment]
@plribeiro3000 you forgot a couple of requires it seems, this causes failures with legacy keys, see:
```
get_object_acl.rb
get_bucket_acl.rb
get_bucket.rb
get_service.rb
copy_object.rb
```
, the relevant require is at the beginning of class:
```
      class Real
        require "fog/google/parsers/storage/copy_object"
```

**Comment by plribeiro3000** [comment]
@Temikus Is is not working? It should work out of the box because now the `Parsers` are being loaded using `autoload` from the main file (`lib/fog/google`).

**Comment by Temikus** [comment]
@plribeiro3000 You moved fog/google/parsers/storage/copy_object to fog/parsers/google/storage/copy_object, while the copy_object.rb specifically requires it:
```
module Fog
  module Storage
    class GoogleJSON
      class Real
        require "fog/google/parsers/storage/copy_object"
```
, which results in:
```
λ ruby storage_json.rb
/Users/temikus/Code/fog-google/lib/fog/storage/google_json/requests/copy_object.rb:5:in `require': cannot load such file -- fog/google/parsers/storage/copy_object (LoadError)
	from /Users/temikus/Code/fog-google/lib/fog/storage/google_json/requests/copy_object.rb:5:in `<class:Real>'
	from /Users/temikus/Code/fog-google/lib/fog/storage/google_json/requests/copy_object.rb:4:in `<class:GoogleJSON>'
	from /Users/temikus/Code/fog-google/lib/fog/storage/google_json/requests/copy_object.rb:3:in `<module:Storage>'
	from /Users/temikus/Code/fog-google/lib/fog/storage/google_json/requests/copy_object.rb:2:in `<module:Fog>'
	from /Users/temikus/Code/fog-google/lib/fog/storage/google_json/requests/copy_object.rb:1:in `<top (required)>'
	from /Users/temikus/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:324:in `require'
	from /Users/temikus/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:324:in `require_item'
	from /Users/temikus/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:301:in `block in require_requests_and_mock'
	from /Users/temikus/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:300:in `each'
	from /Users/temikus/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:300:in `require_requests_and_mock'
	from /Users/temikus/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:139:in `setup_requirements'
	from /Users/temikus/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/fog-core-1.36.0/lib/fog/core/service.rb:100:in `new'
	from /Users/temikus/Code/fog-google/lib/fog/storage/google.rb:15:in `new'
	from storage_json.rb:14:in `test'
	from storage_json.rb:37:in `<main>'
```

**Comment by plribeiro3000** [comment]
Oh, my bad. Will fix it in a minute.

**Comment by plribeiro3000** [comment]
here you go @Temikus. It should be ok now. Just had to remove the explicit requires.
Since the constant is already defined we don't need to require it manually in each file anymore. =)

**Comment by Temikus** [comment]
LGTM :+1: 
Thanks @plribeiro3000, you rock! :rocket: :bomb: :fireworks:

**Pull request merged**
