### PR TITLE
add :storage_class attribute for NEARLINE

### PR DESCRIPTION
**Pull request by face**
Fixes issue #91

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@face Could you configure your git and/or github so you can take ownership of the work you just did?

Thanks!

**Comment by Temikus** [comment]
Tested basic functionality, LGTM :+1:

**Comment by face** [comment]
@plribeiro3000 thanks, I added my work email to my profile, so my commits should be associated with me now.

**Comment by plribeiro3000** [comment]
:+1:

**Comment by plribeiro3000** [comment]
Thank you @face and @Temikus !

**Pull request merged**
