### PR TITLE
Adding rake lint task for rubocop

### PR DESCRIPTION
**Pull request by Temikus**
Do I need to add this to the Travis runs as well or are we using houndCI?

/CC @plribeiro3000

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@Temikus dunno. Are we going to use @houndci? If not we can add this task to the `travis`build.

**Comment by Temikus** [comment]
@plribeiro3000 - Thanks! :) I'm for using @houndci. 
@geemus - what do you think about it? Should I add the integration?

**Comment by geemus** [comment]
I don't think we've used hound previously, but I'm fine if you guys want to give it a shot. Thanks!

**Comment by plribeiro3000** [comment]
I forgot to mention i'm using it in most of the extracted providers and it decreased the amount of time needed to review code by a lot. =)

**Comment by geemus** [comment]
@plribeiro3000 ha, I guess I hadn't noticed. Thanks!

**Comment by plribeiro3000** [comment]
:+1:

**Comment by Temikus** [comment]
Thanks for your comments, I'll add Hound integration soon.

**Comment by plribeiro3000** [comment]
Just so you guys would know how it goes: https://github.com/fog/fog-ecloud/pull/13

**Comment by Temikus** [comment]
Activated hound, confirmed it's working, updated rubocop_todo.
@plribeiro3000 - Looks ok to you? Anything I forgot?

**Comment by plribeiro3000** [comment]
@Temikus Sounds good. What's with all the rules at `.rubocop.yml`?

**Comment by Temikus** [comment]
@plribeiro3000 Those are the default recommended rules and stylings of Hound, you have the same in ecloud: https://github.com/fog/fog-ecloud/blob/master/.rubocop.yml

**Comment by plribeiro3000** [comment]
Really? I did not remember. ahhaha

:+1: then

**Comment by Temikus** [comment]
@plribeiro3000 Thanks! :+1:

**Pull request merged**
