### PR TITLE
Fix missing paging on all models

### PR DESCRIPTION
**Pull request by agrare**

### CODE REVIEW

**Review by Temikus — APPROVED** [review]
This is a wonderful contribution, thank you ❤️

**Comment by agrare** [comment]
Thanks @Temikus !

**Comment by agrare** [comment]
Hey @Temikus! Unless you have bigger plans for master I wonder if you could cut a patch release that includes this fix?

**Comment by Temikus** [comment]
@agrare of course, will do today. Apologies for the delay - I got sick with really bad bronchitis, only just recovered.

**Comment by Temikus** [comment]
@agrare done - https://github.com/fog/fog-google/pull/617

**Pull request merged**
