### PR TITLE
Introducing rubocop linter

### PR DESCRIPTION
**Pull request by Temikus**
Work towards #15 
I recently introduced linters into another project, so quickly made a foundation for fog-google. 
Those tasks should help you work through the issues gradually and ease CI integration in the future somewhat.

Introducing:
1) Linter tasks in a :lint namespace:
```
λ rake lint
lint               -- run rubocop
lint:auto_correct  -- auto-correct rubocop offenses
```
2) .rubocop_todo.yml file, to work through the issues at your own pace.

What do you think?

### CODE REVIEW

**Comment by Temikus** [comment]
Relating to failed builds - those are because one of the dependencies requires Ruby >1.9.2
You still support 1.9.2/1.8.7?
If so - let me know and I'll see if we can hack around that.

**Comment by ihmccreery** [comment]
Per the [fog Roadmap](https://github.com/fog/fog/wiki/Roadmap#20-release), we should still support `1.8.7`.  I think once we pass that barrier, we can also cut support for `1.9.2`.

**Comment by Temikus** [comment]
Yeah, rubocop depends on Ruby >=1.9.2 for a very long time and, in, fact, cannot properly lint 1.8.7-compliant code. Oh well, was worth a try :-P

**Comment by ihmccreery** [comment]
Yes, thanks for the work.  It'd be cool to keep this in the pipeline for v2.

**Pull request closed without merging**
