### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by Temikus**
Fixing up tests so we can rely on CI for breakages. Starting with a rather embarrassing regression I introduced.

### CODE REVIEW

**Comment by Temikus** [comment]
Ahhhh, so it was a parameter, not a rule... 

@icco FYI I fixed hound.

**Comment by Temikus** [comment]
Network model gateway and ipv4 range fields seem to not be functional due to a typo in the GoogleAPI lib: https://github.com/google/google-api-ruby-client/issues/666

I'm not entirely sure how to populate the data properly, since the aliases do not seem to work when instantiating a class, i.e.:
```
network = service.get_network(identity).to_h
[3] pry(#<Fog::Compute::Google::Networks>)> network = service.get_network(identity).to_h
=> {:name=>"fog-test-networkscol-842a61e2-15f3-4179-97ff-7c7a7ffada8b",
 :creation_timestamp=>"2018-04-12T04:01:42.889-07:00",
 :id=>7840112885788476025,
 :kind=>"compute#network",
 :routing_config=>{:routing_mode=>"REGIONAL"},
 :self_link=>"https://www.googleapis.com/compute/v1/projects/myproject/global/networks/fog-test-networkscol-842a61e2-15f3-4179-97ff-7c7a7ffada8b",
 :i_pv4_range=>"10.240.0.0/16",
 :gateway_i_pv4=>"10.240.0.1"}

[4] pry(#<Fog::Compute::Google::Networks>)> new(network)
=>   <Fog::Compute::Google::Network
    name="fog-test-networkscol-842a61e2-15f3-4179-97ff-7c7a7ffada8b",
    auto_create_subnetworks=nil,
    creation_timestamp="2018-04-12T04:01:42.889-07:00",
    description=nil,
    gateway_ipv4=nil,
    ipv4_range=nil,
    id=7840112885788476025,
    kind="compute#network",
    peerings=nil,
    routing_config={:routing_mode=>"REGIONAL"},
    self_link="https://www.googleapis.com/compute/v1/projects/myproject/global/networks/fog-test-networkscol-842a61e2-15f3-4179-97ff-7c7a7ffada8b",
    subnetworks=nil
  >

:| I'll try tackling this tomorrow a bit more.

**Comment by Temikus** [comment]
Ok, one test left to fix.

I'll address Hound with the final commit to not pepper them everywhere and see if anything's failing after changing the hash format.

**Comment by Temikus** [comment]
Ok, so now only some flaky tests are left. Most notably the stackdriver API:
```
 1) Error:
TestMetricDescriptors#test_multiple_timeseries:
Google::Apis::ClientError: badRequest: The provided filter doesn't refer to any known metric.
    /var/lib/gems/2.3.0/gems/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:218:in `check_status'
    /var/lib/gems/2.3.0/gems/google-api-client-0.19.8/lib/google/apis/core/api_command.rb:116:in `check_status'
    /var/lib/gems/2.3.0/gems/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:183:in `process_response'
    /var/lib/gems/2.3.0/gems/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:299:in `execute_once'
    /var/lib/gems/2.3.0/gems/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
    /var/lib/gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
    /var/lib/gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
    /var/lib/gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
    /var/lib/gems/2.3.0/gems/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:101:in `block in execute'
    /var/lib/gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:61:in `block in retriable'
    /var/lib/gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `times'
    /var/lib/gems/2.3.0/gems/retriable-3.1.1/lib/retriable.rb:57:in `retriable'
    /var/lib/gems/2.3.0/gems/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:93:in `execute'
    /var/lib/gems/2.3.0/gems/google-api-client-0.19.8/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
    /var/lib/gems/2.3.0/gems/google-api-client-0.19.8/generated/google/apis/monitoring_v3/service.rb:695:in `list_project_time_series'
    /tmp/build/453021c2/src/fog-google/lib/fog/google/requests/monitoring/list_timeseries.rb:42:in `list_timeseries'
    /tmp/build/453021c2/src/fog-google/test/integration/monitoring/test_timeseries.rb:131:in `test_multiple_timeseries'
```
It's so flaky I think I just need to make a generic wrapper around it in the request itself.

I'll sleep on it.

**Comment by Temikus** [comment]
Apparently this is a known problem with stackdriver metric, sometimes it requires 80+ seconds for the metric to become available:
https://github.com/GoogleCloudPlatform/openjdk-runtime/issues/127

I'll try wrapping everything in backoff `Retriable` unless I come up with any new ideas.

**Comment by Temikus** [comment]
All tests pass \o/

**Comment by Temikus** [comment]
Reran 2 times, some additional flakiness is left. I'll attempt to debug.
Possibly will set operations for model creation to `sync` instead of `async`. That should help with PD flakes but will somewhat increase the test suite run time.

**Comment by Temikus** [comment]
Ok, I'll merge this to be able to test other PR's and open a new branch to fix the leftover disk flakiness.

**Comment by icco** [comment]
Thanks for this!

**Pull request merged**
