### PR TITLE
support for SSL certificates, https proxies and global IP addresses

### PR DESCRIPTION
**Pull request by kamerblauwlicht**
Those features are needed if you want to deploy an HTTP(S) load balancer with Fog and want to use SSL termination.

### CODE REVIEW

**Comment by kamerblauwlicht** [comment]
will fix the hound stuff next week.

**Comment by icco** [comment]
Hi @kamerblauwlicht. Thank you so much for this.

We're currently rewriting all of the request layer of fog-google in #210. If you want, you can redo this to merge into that branch, but you'll have to tweak your request code. Otherwise I can merge into master, so we can do a quicker release and we'll need a second change to change the request layer.

Whichever works for you.

**Comment by kamerblauwlicht** [comment]
@icco please merge with master branch anyway. will update later next week for the new branch.

**Comment by Temikus** [comment]
@kamerblauwlicht This is amazing and badly needed. Thank you so much!

**Pull request merged**
