### PR TITLE
Add Fog Binary for Google

### PR DESCRIPTION
**Pull request by plribeiro3000**
Forgot to move the bin file.

cc/ @icco @erjohnso @ihmccreery

### CODE REVIEW

**Comment by ihmccreery** [comment]
@plribeiro3000 Thanks, this helps.  :)

Can you rebase to master?  I added authors and emails to the `gemspec`.

**Comment by plribeiro3000** [comment]
Sure. Give me a few minutes. =)

**Comment by ihmccreery** [comment]
Wait, no, we need to pull in my PR first.  Sorry, I was confused.

**Comment by plribeiro3000** [comment]
haha. No problem. Can we move forward and merge your PR then?

**Comment by ihmccreery** [comment]
You tell me.  ;)

**Comment by plribeiro3000** [comment]
I can merge it but i don't want to go ahead of the maintainers so thats why i am asking about it. =)

**Comment by plribeiro3000** [comment]
Alright. Its a pretty simple change so lets do this. =)

**Comment by plribeiro3000** [comment]
@ihmccreery I guess a rebase was not need in the end so can we go ahead and merge this one as well?

We need this change to finish the extraction.

**Comment by ihmccreery** [comment]
Sure.  A rebase will keep the commit history cleaner because it won't add an extra merge commit, though.

**Comment by plribeiro3000** [comment]
Alright. Rebased. Going to merge right away. =)

**Comment by plribeiro3000** [comment]
@ihmccreery It might be safe to release it now. =)

**Comment by ihmccreery** [comment]
I'm running a couple of spot tests locally, but I'll release a gem ASAP, and then give you the go-ahead to merge fog/fog#3514.

**Comment by plribeiro3000** [comment]
Gotta keep up the [`CONTRIBUTORS.md`](https://github.com/fog/fog-google/blob/master/CONTRIBUTORS.md) file.

@geemus has a tool for that: [osrcry](https://github.com/geemus/osrcry) but it does not help much here because we already have a ton of contributors from `fog` that does not have commit here so it will just drop all of them. What i'm doing so far is update it by hand but i guess that a provider of the size of this one can keep it going like this.

Perhaps we might send some patches to @geemus. =)

**Comment by ihmccreery** [comment]
Cool.  Can you open a separate issue for that?  I don't want us to lose track of it.

**Comment by plribeiro3000** [comment]
Yeah. Let me do this.

**Pull request merged**
