### PR TITLE
Use relative paths

### PR DESCRIPTION
**Pull request by plribeiro3000**
This is a WIP. Since i can't run the tests from my machine i will see the result in travis.

@ihmccreery Can you help me out setup a test env in my machine or i do need a real access key from google cloud engine?

### CODE REVIEW

**Comment by icco** [comment]
To test the live API, you'll need a Google access key. Otherwise the tests work the same as they do for the rest of fog. Travis just runs the mock tests.

`export FOG_MOCK=true && bundle exec shindont`

At some point, maybe @ihmccreery can set up an API key for Travis using http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables, but that wouldn't test pull requests.. so I don't know.

**Comment by ihmccreery** [comment]
Thanks for the work!

@icco: see #19.  This has been under discussion for some time, but the safety of using Travis encrypted variables hasn't been settled.

@plribeiro3000: Travis CI success is necessary, but not sufficient.  Please fix the broken Travis tests, (or, if they're borked and aren't worth fixing, we can discuss more,) and we can work on integration testing.  I don't have bandwidth this week to help out, but @erjohnso might be able to, or I can hopefully find some time next week.  Sorry to drag.

**Comment by plribeiro3000** [comment]
awesome @ihmccreery !

I'm currently working towards fog/fog#3430. Somehow i left fog-google out of the game. =s

So there is several points to tackle:

- [ ] Use the main file ([`google.rb`](https://github.com/fog/fog-google/blob/master/lib/fog/google.rb)) as the main load point
- [ ] Load everything else using `autoload`
- [ ] Use relative paths (compatible with ruby `1.8.7` for now)
- [ ] Follow the namespace to place files

This last one is not really necessary but it would help maintainability over several projects since you can easily find the file because there is a pattern.

LMK your thoughts.

Regarding the build, i will try to fix it asap.

**Comment by ihmccreery** [comment]
@erjohnso, can you pick this up please?  Thanks.

**Comment by plribeiro3000** [comment]
Sorry for the delay here. I will get back to it asap.

**Comment by plribeiro3000** [comment]
Sorry for the delay on this guys. A lot changed since i've started working on this. A rebase will be painfull so i will restart the work from scratch. Will try to do baby steps this time to avoid this kind of issue again.

**Pull request closed without merging**
