### PR TITLE
[WIP] Adding Proxy support

### PR DESCRIPTION
**Pull request by juliancheal**
As mentioned in issue #153 the Google Api client supports proxies.
This is an inital work in progress at getting proxy support in fog-google.

This is my first look at the fog-google gem, so I'm not that familiar.

I know this PR isn't complete, but thought I'd make an initial attempt and ask for feedback on what exactly else needs doing to get proxy support into fog-google.

Thanks :)

### CODE REVIEW

**Comment by Temikus** [comment]
Hi @juliancheal ! Thanks for the PR! :)

I see that the option is already exposed in variable by setting `http_proxy` variable. Which is, IMO, correct since prod proxies usually include some sort of credentials.
Or am I missing some specific use-case for an argument?

**Comment by juliancheal** [comment]
Hey @Temikus.

I'm trying to set the proxy settings from ManageIQ. This is the PR I'm currently working on https://github.com/ManageIQ/manageiq/pull/10368

**Comment by Temikus** [comment]
@juliancheal Ah, makes sense now. Thanks for the reference!

Just a couple of notes then:
- Did you take a look what happens if the `http_proxy` is set? Would the parameter be overriden?
- Did you check whether it works the same with API client 0.9? We're going to migrate soon.

**Comment by juliancheal** [comment]
> Did you take a look what happens if the http_proxy is set? Would the parameter be overridden?

Do you mean setting `http_proxy` as an environment variable. The problem with that is customers want to be able to set separate proxies for different providers, i.e. amazon, google, azure. So setting a global env wouldn't work in this case.

> Did you check whether it works the same with API client 0.9? We're going to migrate soon.

I've not, I'll give that a go, and make sure it works there too. Thanks for the heads up. :)

**Comment by Temikus** [comment]
@juliancheal 
> Do you mean setting http_proxy as an environment variable. The problem with that is customers want to be able to set separate proxies for different providers, i.e. amazon, google, azure. So setting a global env wouldn't work in this case.

If you look closely `google-api-client` already implements the logic for taking the environment variable in and setting it as a proxy parameter.
What I meant is - make sure that the lib itself doesn't explode if you set both the `proxy:` in fog and have `http_proxy` set for any reason.

> I've not, I'll give that a go, and make sure it works there too. Thanks for the heads up. :)
 Cool, thanks 👍

**Comment by juliancheal** [comment]
> If you look closely google-api-client already implements the logic for taking the environment variable in and setting it as a proxy parameter.
> What I meant is - make sure that the lib itself doesn't explode if you set both the proxy: in fog and have http_proxy set for any reason.

Ah, now I see what you mean. Thanks @Temikus :)

**Comment by selmanj** [comment]
Instead of adding a `proxy` parameter, would it be better to add a `google_client_options` hash that will be directly passed to the underlying google client?  I'm not sure if fog-google needs to be aware of any of these options, and in the future it would allow consumers to make changes to the underlying client without having to 'poke a hole' like this PR does.

@Temikus what do you think?

**Comment by Temikus** [comment]
@selmanj - That is a good idea. 

However, our stats depend on `application_` options in that hash, so one needs to make sure those are not overwritten.

**Comment by juliancheal** [comment]
Sorry for my absence on this PR, have been away traveling.

I've updated this PR (if it were to be merged I will squish the commits) with the suggestion from @selmanj of creating a `google_client_options` hash.

**Comment by Temikus** [comment]
Sorry it took a while. Thanks @juliancheal!

**Comment by juliancheal** [comment]
Hi @Temikus no problem, thanks for merging 😄

**Pull request merged**
