### PR TITLE
Check for empty snapshots when listing

### LINKED ISSUE #239: Compute client throws when listing snapshots
When no snapshots exist and `snapshots.all` is called on a compute client, an error is thrown:
```
TypeError: no implicit conversion of nil into Array
    /Users/jsselman/src/fog-google/lib/fog/compute/google/models/snapshots.rb:12:in `concat'
    /Users/jsselman/src/fog-google/lib/fog/compute/google/models/snapshots.rb:12:in `block in all'
    /Users/jsselman/src/fog-google/lib/fog/compute/google/models/snapshots.rb:10:in `loop'
    /Users/jsselman/src/fog-google/lib/fog/compute/google/models/snapshots.rb:10:in `all'
```

Regression introduced in #222 , reported by @agrare

### PR DESCRIPTION
**Pull request by selmanj**
Fixes #239 

I added a bare-bones test, obviously I don't think this is sufficiently testing snapshot functionality but I figured something is better than nothing.

/cc @agrare

### CODE REVIEW

**Comment by agrare** [comment]
:+1: can confirm this fixes my issue.

Before this change:
```
connection.snapshots.all
TypeError: no implicit conversion of nil into Array
	from /var/lib/gems/2.3.0/gems/fog-google-0.5.3/lib/fog/compute/google/models/snapshots.rb:12:in `concat'
	from /var/lib/gems/2.3.0/gems/fog-google-0.5.3/lib/fog/compute/google/models/snapshots.rb:12:in `block in all'
	from /var/lib/gems/2.3.0/gems/fog-google-0.5.3/lib/fog/compute/google/models/snapshots.rb:10:in `loop'
	from /var/lib/gems/2.3.0/gems/fog-google-0.5.3/lib/fog/compute/google/models/snapshots.rb:10:in `all'
```

After this change

```
connection.snapshots.all
   <Fog::Compute::Google::Snapshots
    [
          
    ]
  >
```

Thanks @selmanj !

**Comment by agrare** [comment]
@selmanj @icco is it possible to get a release tagged for this?

**Comment by icco** [comment]
Sure, I'll do one now

**Comment by agrare** [comment]
Thanks!

**Pull request merged**
