### PR TITLE
Lint cleanup

### PR DESCRIPTION
**Pull request by icco**
@plribeiro3000 not sure who I should send my code reviews to these days... not sure what the status is over in Google employee land. But I ran `rubocop -a` on the directory for giggles, and got this. 

All of it makes sense, and tests pass.

/cc @ihmccreery @Temikus

### CODE REVIEW

**Comment by icco** [comment]
This is, in my mind, progress towards #34.

**Comment by plribeiro3000** [comment]
@icco I think this is pretty straight forward. If you think this is good to go lets merge it. =)

**Comment by plribeiro3000** [comment]
:+1: Maybe we should add `rubocop` to the build. What do you think?

**Comment by Temikus** [comment]
@plribeiro3000 @icco I was thinking of ressurecting #48, since we don't rely on 1.9.3. anymore. Would that work?

**Comment by plribeiro3000** [comment]
@Temikus Ops. Didn't know you had already work towards this. Sorry.
Since this one was merged i believe we can move from here. We just need to make `rubocop` run in Travis as well. 

I'm not sure what you guys think but i'm using @houndci to handle this and i kind of like it. =)
It is a spammer but at least i don't have to go to the build to see whats wrong. =)

**Comment by Temikus** [comment]
@plribeiro3000 Not a problem at all :) With this merged, the only thing left is to add a rake task and add it to travis. I think with a variable `LINTER=TRUE` or something.

I'm all for trying to use hound. The question is whether their free tier is allowed for our use-case.
And, AFAIK it's only a linter, so not exactly replacement for our Travis setup.

**Comment by icco** [comment]
I'm down with @houndci or just adding it to the build or whatever. Thankfully github allows for multiple CIs on the same pull request.

**Pull request merged**
